// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc6ZHwYQoInXXmfZpm3bnJTKKdXOpxnYk',
    appId: '1:535959979906:web:9d0f978d09bf7cf284b19b',
    messagingSenderId: '535959979906',
    projectId: 'provider-learning-cfe00',
    authDomain: 'provider-learning-cfe00.firebaseapp.com',
    storageBucket: 'provider-learning-cfe00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEvPQmP2XHyPMkR0ItGnzliI1hDluSiaE',
    appId: '1:535959979906:android:2a111fc9fbbf29bc84b19b',
    messagingSenderId: '535959979906',
    projectId: 'provider-learning-cfe00',
    storageBucket: 'provider-learning-cfe00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFjihGZJCVX0kLlkAgC6MlaWBUQ9zHfHg',
    appId: '1:535959979906:ios:98bc680ceec0ac2d84b19b',
    messagingSenderId: '535959979906',
    projectId: 'provider-learning-cfe00',
    storageBucket: 'provider-learning-cfe00.appspot.com',
    iosClientId: '535959979906-kf7htu1scqvnvj0kle0j36uiho35n6ct.apps.googleusercontent.com',
    iosBundleId: 'com.example.providerLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFjihGZJCVX0kLlkAgC6MlaWBUQ9zHfHg',
    appId: '1:535959979906:ios:0e7472ed072946a984b19b',
    messagingSenderId: '535959979906',
    projectId: 'provider-learning-cfe00',
    storageBucket: 'provider-learning-cfe00.appspot.com',
    iosClientId: '535959979906-d8m0hgchjl2ovs8jhsk6t5sn8kamj5nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.providerLearning.RunnerTests',
  );
}
